const data = {
  products: [
    {
      _id: "1",
      name: "Free Shirt",
      slug: "free-shirt",
      price: 9.99,
      image: "/images/image1.png",
      description: "Product 1 description",
      category: "Shirts",
      rating: 4.5,
      numReviews: 10,
      countInStock: 5,
      brand: "Adidas",
      colors: ["red", "green", "blue", "yellow", "orange"],
      size: ["small", "medium", "large"],
    },
    {
      _id: "2",
      name: "Fit Pants",
      slug: "fit-pants",
      price: 19.99,
      image: "/images/image2.png",
      description: "Product 2 description",
      category: "Pants",
      rating: 4.5,
      numReviews: 10,
      countInStock: 5,
      brand: "Samsung",
      colors: ["red", "green", "blue", "yellow", "orange"],
      size: ["small", "medium", "large"],
    },
    {
      _id: "3",
      name: "Casual T-Shirt",
      slug: "casual-t-shirt",
      price: 14.99,
      image: "/images/image3.png",
      description: "Product 3 description",
      category: "Shirts",
      rating: 4.2,
      numReviews: 8,
      countInStock: 7,
      brand: "Nike",
      colors: ["black", "white", "gray", "navy"],
      size: ["small", "medium", "large", "extra-large"],
    },
    {
      _id: "4",
      name: "Sport Shorts",
      slug: "sport-shorts",
      price: 24.99,
      image: "/images/image4.png",
      description: "Product 4 description",
      category: "Shorts",
      rating: 4.7,
      numReviews: 12,
      countInStock: 3,
      brand: "Under Armour",
      colors: ["black", "navy", "gray"],
      size: ["small", "medium", "large"],
    },
    {
      _id: "5",
      name: "Running Shoes",
      slug: "running-shoes",
      price: 49.99,
      image: "/images/image5.png",
      description: "Product 5 description",
      category: "Shoes",
      rating: 4.8,
      numReviews: 15,
      countInStock: 10,
      brand: "Asics",
      colors: ["black", "white", "blue"],
      size: ["7", "8", "9", "10"],
    },
    {
      _id: "6",
      name: "Yoga Mat",
      slug: "yoga-mat",
      price: 29.99,
      image: "/images/image6.png",
      description: "Product 6 description",
      category: "Fitness",
      rating: 4.6,
      numReviews: 11,
      countInStock: 4,
      brand: "Lululemon",
      colors: ["purple", "pink", "blue", "green"],
      size: ["standard", "extra-thick"],
    },
    {
      _id: "7",
      name: "Gym Bag",
      slug: "gym-bag",
      price: 39.99,
      image: "/images/image7.png",
      description: "Product 7 description",
      category: "Accessories",
      rating: 4.4,
      numReviews: 9,
      countInStock: 6,
      brand: "Puma",
      colors: ["black", "red", "gray"],
      size: ["small", "medium"],
    },
    {
      _id: "8",
      name: "Baseball Cap",
      slug: "baseball-cap",
      price: 12.99,
      image: "/images/image8.png",
      description: "Product 8 description",
      category: "Hats",
      rating: 4.3,
      numReviews: 7,
      countInStock: 8,
      brand: "New Era",
      colors: ["black", "white", "navy", "gray"],
      size: ["one size"],
    },
    {
      _id: "9",
      name: "Water Bottle",
      slug: "water-bottle",
      price: 7.99,
      image: "/images/image9.png",
      description: "Product 9 description",
      category: "Accessories",
      rating: 4.0,
      numReviews: 6,
      countInStock: 12,
      brand: "Camelbak",
      colors: ["blue", "green", "pink", "purple"],
      size: ["20oz", "32oz"],
    },
    {
      _id: "10",
      name: "Sweatshirt",
      slug: "sweatshirt",
      price: 34.99,
      image: "/images/image10.png",
      description: "Product 10 description",
      category: "Sweatshirts",
      rating: 4.7,
      numReviews: 10,
      countInStock: 5,
      brand: "Champion",
      colors: ["black", "gray", "navy"],
      size: ["small", "medium", "large", "extra-large"],
    },
  ],
};

export default data;
